backend:
  name: git-gateway
  repo: jdvne/bbpoison.xyz
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
# publish_mode: editorial_workflow

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://bbpoison.xyz
display_url: https://bbpoison.xyz

# logo_url:


collections:
  - label: "Art"
    name: "art"
    extension: json
    format: json
    folder: "src/content/art"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - {label: "External Link", name: "link", widget: "string", required: false}

  - label: "Pages"
    name: "pages"
    files: 
      - label: "Home"
        name: "home"
        file: "src/content/pages/home.json"
        fields:
          - { label: "Bio", name: "bio", widget: "markdown" }
          - {
              label: "Artworks", name: "artworks", widget: "list", 
              summary: '{{fields.art}}',
              field: {
                label: "Art", 
                name: "art", 
                widget: "relation",
                collection: "art",
                search_fields: ["title", "slug"],
                value_field: "{{slug}}",
                display_fields: ["title"]
              }
            }

  - label: "Galleries"
    name: "galleries"
    extension: json
    format: json
    folder: "src/content/galleries"
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - {label: "External Link", name: "link", widget: "string", required: false}
      - {
          label: "Artworks", name: "artworks", widget: "list", 
          summary: '{{fields.art}}',
          field: {
            label: "Art", 
            name: "art", 
            widget: "relation",
            collection: "art",
            search_fields: ["title", "slug"],
            value_field: "{{slug}}",
            display_fields: ["title"]
          }
        }